import { Router } from "express";
import { z } from "zod";
import { pool, withTransaction } from "../config/db";
import { AppError } from "../middleware/error";
import { requireAuth, requireRole } from "../middleware/auth";

export const shopRouter = Router();
const parseJson = <T>(value: T | string | null, fallback: T): T => value == null ? fallback : typeof value === "string" ? JSON.parse(value) : value;
const productOut = (row: any) => ({ id:Number(row.id), slug:row.slug, name:row.name, description:row.description||"", category:row.category, price:Number(row.price), compareAt:row.compare_at_price==null?undefined:Number(row.compare_at_price), image:row.image_url, images:parseJson(row.images,[]), colors:parseJson(row.colors,[]), sizes:parseJson(row.sizes,[]), badge:row.badge||undefined, inventory:Number(row.inventory), featured:Boolean(row.featured), status:row.status });

shopRouter.get("/products", async (req,res,next)=>{try{ const featured=req.query.featured==="true"; const category=typeof req.query.category==="string"?req.query.category:undefined; const params:any={}; let where="status='active'"; if(featured)where+=" AND featured=1"; if(category){where+=" AND category=:category";params.category=category} const [rows]=await pool.execute(`SELECT * FROM shop_products WHERE ${where} ORDER BY featured DESC, created_at DESC`,params); res.json({products:(rows as any[]).map(productOut)}); }catch(e){next(e)}});
shopRouter.get("/products/:slug", async(req,res,next)=>{try{const slug=z.string().trim().min(2).max(160).parse(req.params.slug);const [rows]=await pool.execute("SELECT * FROM shop_products WHERE slug=:slug AND status='active' LIMIT 1",{slug});const row=(rows as any[])[0];if(!row)throw new AppError(404,"Product not found");res.json({product:productOut(row)});}catch(e){next(e)}});
shopRouter.get("/collections",async(_req,res,next)=>{try{const [rows]=await pool.execute("SELECT category AS name, COUNT(*) AS productCount, MIN(image_url) AS image FROM shop_products WHERE status='active' GROUP BY category ORDER BY category");res.json({collections:rows});}catch(e){next(e)}});

const orderSchema=z.object({customer:z.object({email:z.string().email(),firstName:z.string().min(1).max(100),lastName:z.string().min(1).max(100),phone:z.string().max(40).optional()}),shippingAddress:z.object({address:z.string().min(5).max(500),city:z.string().min(2).max(100),state:z.string().min(2).max(100),postalCode:z.string().min(4).max(12),country:z.string().default("India")}),items:z.array(z.object({productId:z.number().int().positive(),quantity:z.number().int().min(1).max(20),variant:z.string().max(120).optional()})).min(1).max(50),paymentMethod:z.enum(["cod","razorpay"]).default("cod"),notes:z.string().max(1000).optional()});
shopRouter.post("/orders",async(req,res,next)=>{try{const input=orderSchema.parse(req.body);const result=await withTransaction(async db=>{const ids=input.items.map(x=>x.productId);const placeholders=ids.map(()=>"?").join(",");const [rows]=await db.query(`SELECT id,name,price,inventory FROM shop_products WHERE status='active' AND id IN (${placeholders}) FOR UPDATE`,ids);const products=rows as any[];if(products.length!==new Set(ids).size)throw new AppError(400,"One or more products are unavailable");const items=input.items.map(item=>{const p=products.find(x=>Number(x.id)===item.productId);if(p.inventory<item.quantity)throw new AppError(409,`${p.name} has insufficient stock`);return {...item,name:p.name,unitPrice:Number(p.price),total:Number(p.price)*item.quantity}});const subtotal=items.reduce((n,x)=>n+x.total,0);const shipping=subtotal>=3500?0:199;const [customerResult]:any=await db.execute(`INSERT INTO shop_customers(email,first_name,last_name,phone) VALUES(:email,:firstName,:lastName,:phone) ON DUPLICATE KEY UPDATE first_name=VALUES(first_name),last_name=VALUES(last_name),phone=VALUES(phone),id=LAST_INSERT_ID(id)`,{...input.customer,phone:input.customer.phone||null});const customerId=Number(customerResult.insertId);const orderNumber=`NRD-${Date.now().toString().slice(-8)}`;const [orderResult]:any=await db.execute(`INSERT INTO shop_orders(order_number,customer_id,payment_method,subtotal,shipping_total,total,shipping_address,notes) VALUES(:orderNumber,:customerId,:paymentMethod,:subtotal,:shipping,:total,:address,:notes)`,{orderNumber,customerId,paymentMethod:input.paymentMethod,subtotal,shipping,total:subtotal+shipping,address:JSON.stringify(input.shippingAddress),notes:input.notes||null});for(const item of items){await db.execute("INSERT INTO shop_order_items(order_id,product_id,product_name,variant,quantity,unit_price,total) VALUES(?,?,?,?,?,?,?)",[orderResult.insertId,item.productId,item.name,item.variant||null,item.quantity,item.unitPrice,item.total]);await db.execute("UPDATE shop_products SET inventory=inventory-? WHERE id=?",[item.quantity,item.productId])}await db.execute("UPDATE shop_customers SET orders_count=orders_count+1,total_spent=total_spent+? WHERE id=?",[subtotal+shipping,customerId]);return {id:orderResult.insertId,orderNumber,total:subtotal+shipping,status:"pending"};});res.status(201).json({order:result});}catch(e){next(e)}});

const eventSchema=z.object({eventName:z.string().min(1).max(100),eventId:z.string().max(100).optional(),sessionId:z.string().max(100).optional(),pagePath:z.string().max(500).optional(),properties:z.record(z.string(),z.unknown()).optional()});
shopRouter.post("/events",async(req,res,next)=>{try{const e=eventSchema.parse(req.body);await pool.execute("INSERT INTO shop_events(event_name,event_id,session_id,page_path,properties) VALUES(:eventName,:eventId,:sessionId,:pagePath,:properties)",{...e,eventId:e.eventId||null,sessionId:e.sessionId||null,pagePath:e.pagePath||null,properties:e.properties?JSON.stringify(e.properties):null});res.status(202).json({ok:true});}catch(e){next(e)}});
shopRouter.use("/admin", requireAuth, requireRole("admin"));
shopRouter.get("/admin/dashboard",async(_req,res,next)=>{try{const [[sales],[orders],[customers],[inventory]]:any=await Promise.all([pool.query("SELECT COALESCE(SUM(total),0) total FROM shop_orders WHERE status <> 'cancelled'"),pool.query("SELECT COUNT(*) count FROM shop_orders"),pool.query("SELECT COUNT(*) count FROM shop_customers"),pool.query("SELECT COALESCE(SUM(inventory),0) count FROM shop_products WHERE status='active'")]);res.json({sales:Number(sales[0].total),orders:Number(orders[0].count),customers:Number(customers[0].count),inventory:Number(inventory[0].count)});}catch(e){next(e)}});
shopRouter.get("/admin/orders",async(_req,res,next)=>{try{const [rows]=await pool.execute("SELECT o.*, CONCAT(c.first_name,' ',c.last_name) customer_name,c.email customer_email FROM shop_orders o JOIN shop_customers c ON c.id=o.customer_id ORDER BY o.created_at DESC");res.json({orders:rows});}catch(e){next(e)}});
shopRouter.get("/admin/customers",async(_req,res,next)=>{try{const [rows]=await pool.execute("SELECT id,email,first_name,last_name,phone,orders_count,total_spent,created_at FROM shop_customers ORDER BY created_at DESC");res.json({customers:rows});}catch(e){next(e)}});
shopRouter.get("/admin/products",async(_req,res,next)=>{try{const [rows]=await pool.execute("SELECT * FROM shop_products ORDER BY created_at DESC");res.json({products:(rows as any[]).map(productOut)});}catch(e){next(e)}});
shopRouter.get("/admin/products/:id",async(req,res,next)=>{try{const id=z.coerce.number().int().positive().parse(req.params.id);const [rows]=await pool.execute("SELECT * FROM shop_products WHERE id=:id LIMIT 1",{id});const row=(rows as any[])[0];if(!row)throw new AppError(404,"Product not found");res.json({product:productOut(row)});}catch(e){next(e)}});

const productSchema=z.object({slug:z.string().min(2).max(160).regex(/^[a-z0-9-]+$/),name:z.string().min(2).max(220),description:z.string().max(5000).default(""),category:z.string().min(2).max(120),price:z.number().positive(),compareAt:z.number().positive().nullable().optional(),image:z.string().url().max(1000),colors:z.array(z.string()).max(20).default([]),sizes:z.array(z.string()).max(30).default([]),badge:z.string().max(60).nullable().optional(),inventory:z.number().int().min(0),status:z.enum(["draft","active","archived"]).default("active"),featured:z.boolean().default(false)});
shopRouter.post("/admin/products",async(req,res,next)=>{try{const p=productSchema.parse(req.body);const [result]:any=await pool.execute(`INSERT INTO shop_products(slug,name,description,category,price,compare_at_price,image_url,colors,sizes,badge,inventory,status,featured) VALUES(:slug,:name,:description,:category,:price,:compareAt,:image,:colors,:sizes,:badge,:inventory,:status,:featured)`,{...p,compareAt:p.compareAt||null,colors:JSON.stringify(p.colors),sizes:JSON.stringify(p.sizes),badge:p.badge||null,featured:p.featured?1:0});res.status(201).json({product:{...p,id:result.insertId}});}catch(e){next(e)}});
shopRouter.put("/admin/products/:id",async(req,res,next)=>{try{const id=z.coerce.number().int().positive().parse(req.params.id);const p=productSchema.parse(req.body);const [result]:any=await pool.execute(`UPDATE shop_products SET slug=:slug,name=:name,description=:description,category=:category,price=:price,compare_at_price=:compareAt,image_url=:image,colors=:colors,sizes=:sizes,badge=:badge,inventory=:inventory,status=:status,featured=:featured WHERE id=:id`,{...p,id,compareAt:p.compareAt||null,colors:JSON.stringify(p.colors),sizes:JSON.stringify(p.sizes),badge:p.badge||null,featured:p.featured?1:0});if(!result.affectedRows)throw new AppError(404,"Product not found");res.json({product:{...p,id}});}catch(e){next(e)}});
shopRouter.patch("/admin/orders/:id/status",async(req,res,next)=>{try{const id=z.coerce.number().int().positive().parse(req.params.id);const {status}=z.object({status:z.enum(["pending","paid","processing","shipped","delivered","cancelled"])}).parse(req.body);const [result]:any=await pool.execute("UPDATE shop_orders SET status=:status WHERE id=:id",{id,status});if(!result.affectedRows)throw new AppError(404,"Order not found");res.json({id,status});}catch(e){next(e)}});
shopRouter.get("/admin/settings",async(_req,res,next)=>{try{const [rows]=await pool.execute("SELECT * FROM shop_settings WHERE id=1");res.json({settings:(rows as any[])[0]});}catch(e){next(e)}});
shopRouter.put("/admin/settings",async(req,res,next)=>{try{const s=z.object({storeName:z.string().min(2).max(180),supportEmail:z.string().email(),currency:z.string().length(3),country:z.string().min(2).max(100),freeShippingThreshold:z.number().min(0),flatShippingRate:z.number().min(0),codEnabled:z.boolean()}).parse(req.body);await pool.execute(`UPDATE shop_settings SET store_name=:storeName,support_email=:supportEmail,currency=:currency,country=:country,free_shipping_threshold=:freeShippingThreshold,flat_shipping_rate=:flatShippingRate,cod_enabled=:codEnabled WHERE id=1`,{...s,codEnabled:s.codEnabled?1:0});res.json({settings:s});}catch(e){next(e)}});
