ALTER TABLE shop_products ADD COLUMN source_reference VARCHAR(1000) NULL;
ALTER TABLE shop_products ADD COLUMN trend_signal VARCHAR(500) NULL;

INSERT INTO shop_products
  (slug,name,description,category,price,compare_at_price,image_url,colors,sizes,badge,inventory,status,featured,source_reference,trend_signal)
VALUES
  ('embroidered-rayon-3-piece-set','Embroidered Rayon 3-Piece Set','A fluid rayon kurta, comfortable trousers, and a coordinated dupatta finished with delicate neckline embroidery.','Ethnic Wear',1290,1790,'https://images.meesho.com/images/products/346396061/hygo7_512.webp?width=720','["#7d2828","#203b35","#e4cdbb"]','["S","M","L","XL","XXL"]','Trending',42,'active',1,'https://www.meesho.com/rayon-neck-emroidery-3-pc-suit-for-woman-fashion/p/5q8gwt','Meesho Trending Now; 122k+ reviews; Meta active-ad cluster'),
  ('chanderi-cotton-dupatta-set','Chanderi Cotton Dupatta Set','A light Chanderi-inspired cotton set with a softly structured kurta and an airy occasion-ready dupatta.','Ethnic Wear',1490,1990,'https://images.meesho.com/images/products/481263934/jcg7p_512.webp?width=720','["#bd8767","#d7c9a7","#233b48"]','["S","M","L","XL","XXL"]','Top rated',36,'active',1,'https://www.meesho.com/chitrarekha-pretty-women-kurta-sets/p/7yj5mm','Meesho Trusted; 53k+ reviews; cotton dupatta demand'),
  ('palazzo-dupatta-coord-set','Palazzo & Dupatta Co-ord Set','An easy three-piece silhouette pairing a straight kurta with relaxed palazzo trousers and a tonal dupatta.','Ethnic Wear',1390,1890,'https://images.meesho.com/images/products/501954274/lmkov_512.webp?width=720','["#8e5646","#d5b28c","#283d33"]','["S","M","L","XL","XXL"]','New',30,'active',0,'https://www.meesho.com/cotton-reyon-women-kurti-pallazo-dupatta-set/p/8aumea','Meesho Trending Now; palazzo + dupatta format'),
  ('handblock-rayon-kurta-set','Handblock Rayon Kurta Set','A breathable three-piece rayon set with handblock-inspired motifs and restrained neckline embroidery.','Ethnic Wear',1190,1690,'https://images.meesho.com/images/products/385117168/aopte_512.webp?width=720','["#efe8d9","#9d3f36","#243f56"]','["S","M","L","XL","XXL","3XL"]','Bestseller',48,'active',1,'https://www.meesho.com/rayon-3-pc-set-for-woman-fashion-white-emroidery-neck-suit-pc-printed-hand-block/p/6daeb4','Meesho Trending Now; 30k+ reviews; Meta rayon-set ads'),
  ('muslin-sequin-dupatta-set','Muslin Sequin Dupatta Set','Soft muslin, subtle sequin accents, stretch trousers, and a flowing dupatta for understated festive dressing.','Ethnic Wear',1690,2290,'https://images.meesho.com/images/products/202216747/vfoyy_512.webp?width=720','["#9b6f54","#1d3c3a","#d8c8b5"]','["S","M","L","XL","XXL"]','Top rated',26,'active',1,'https://www.meesho.com/maslin-sequnce-kurta-dupatta-set-with-strechble-pant-dupatta-set/p/3ce7fv','Meesho 44k+ reviews; festive three-piece demand'),
  ('olive-rayon-slub-dupatta-set','Olive Rayon Slub Dupatta Set','An embroidered olive rayon-slub kurta with matching pants and dupatta, designed for everyday polish.','Ethnic Wear',1090,1490,'https://images.meesho.com/images/products/546542300/uuytk_512.webp?width=720','["#66704a","#b29d75"]','["S","M","L","XL","XXL"]','Trending',40,'active',0,'https://www.meesho.com/womens-attractive-olive-reyon-slub-embroidered-kurta-pant-dupatta-set/p/91eaqk','Meesho Trending Now; 22k+ reviews; embroidered rayon signal')
ON DUPLICATE KEY UPDATE
  name=VALUES(name),description=VALUES(description),price=VALUES(price),compare_at_price=VALUES(compare_at_price),image_url=VALUES(image_url),colors=VALUES(colors),sizes=VALUES(sizes),badge=VALUES(badge),inventory=VALUES(inventory),status=VALUES(status),featured=VALUES(featured),source_reference=VALUES(source_reference),trend_signal=VALUES(trend_signal);
