CREATE TABLE IF NOT EXISTS retailx_einvoice_records (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  table_prefix VARCHAR(100) NOT NULL,
  invoice_no VARCHAR(50) NOT NULL,
  bill_performa VARCHAR(20) NOT NULL DEFAULT 'bills',
  invoice_date DATE NULL,
  seller_gstin VARCHAR(15) NOT NULL,
  buyer_gstin VARCHAR(15) NULL,
  status ENUM('NOT_GENERATED', 'PROCESSING', 'GENERATED', 'FAILED', 'CANCELLED') NOT NULL DEFAULT 'NOT_GENERATED',
  request_hash CHAR(64) NULL,
  request_json JSON NULL,
  response_json JSON NULL,
  irn VARCHAR(100) NULL,
  ack_no VARCHAR(50) NULL,
  ack_date VARCHAR(40) NULL,
  signed_invoice LONGTEXT NULL,
  signed_qr_code LONGTEXT NULL,
  eway_bill_no VARCHAR(50) NULL,
  eway_bill_date VARCHAR(40) NULL,
  eway_bill_valid_till VARCHAR(40) NULL,
  eway_bill_cancelled_at DATETIME NULL,
  error_code VARCHAR(100) NULL,
  error_message TEXT NULL,
  cancelled_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_retailx_einvoice_bill (table_prefix, invoice_no, bill_performa),
  KEY idx_retailx_einvoice_irn (irn),
  KEY idx_retailx_einvoice_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
